# Generated by Django 4.0.6 on 2022-08-01 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('money_flow_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('short_desc', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('category', models.CharField(choices=[('Housing', 'Housing'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Utilites', 'Utilities'), ('Clothing', 'Clothing'), ('Healthcare', 'Healthcare'), ('Insurance', 'Insurance'), ('Supplies', 'Supplies'), ('Personal', 'Personal'), ('Debt', 'Debt'), ('Retirement', 'Retirement'), ('Education', 'Education'), ('Savings', 'Savings'), ('Donations', 'Donations'), ('Entertainment', 'Entertainment'), ('Other', 'Other'), ('External income', 'Ex Income')], db_index=True, max_length=15)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shared', models.ManyToManyField(blank=True, db_index=True, related_name='shared_money_flow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
